const CHAMPION_LIST = {
	aatrox: ['aatrox'],
	ahri: ['ahri'],
	akali: ['akali'],
	akshan: ['akshan'],
	alistar: ['alistar'],
	amumu: ['amumu'],
	anivia: ['anivia'],
	annie: ['annie'],
	aphelios: ['aphelios'],
	ashe: ['ashe'],
	aurelionsol: ['aurelionsol', 'aurelion', 'asol', 'sol'],
	azir: ['azir'],
	bard: ['bard', 'bardo'],
	belveth: ['belveth', 'bel veth', 'bel\'veth'],
	blitzcrank: ['blitzcrank', 'blitz'],
	brand: ['brand'],
	braum: ['braum'],
	briar: ['briar'],
	caitlyn: ['caitlyn'],
	camille: ['camille'],
	cassiopeia: ['cassiopeia', 'cass'],
	chogath: ['chogath', 'cho', 'cho gath'],
	corki: ['corki'],
	darius: ['darius'],
	diana: ['diana'],
	draven: ['draven'],
	drMundo: ['drmundo', 'mundo', 'dr mundo'],
	ekko: ['ekko'],
	elise: ['elise'],
	evelynn: ['evelynn', 'eve'],
	ezreal: ['ezreal', 'ez'],
	fiddlesticks: ['fiddlesticks', 'fiddle', 'sticks'],
	fiora: ['fiora'],
	fizz: ['fizz'],
	galio: ['galio'],
	gangplank: ['gangplank', 'gp'],
	garen: ['garen'],
	gnar: ['gnar'],
	gragas: ['gragas'],
	graves: ['graves'],
	gwen: ['gwen'],
	hecarim: ['hecarim', 'heca'],
	heimerdinger: ['heimerdinger', 'heimer', 'donger'],
	hwei: ['hwei', 'huawei', 'huaweiwei'],
	illaoi: ['illaoi'],
	irelia: ['irelia'],
	ivern: ['ivern'],
	janna: ['janna'],
	jarvaniv: ['jarvaniv', 'jarvan', 'j4', 'jiv', 'jarvan4', 'jarvan iv', 'jarvan 4'],
	jax: ['jax'],
	jayce: ['jayce'],
	jhin: ['jhin'],
	jinx: ['jinx'],
	ksante: ['ksante', 'k sante', 'k\'sante', 'kasante'],
	kaisa: ['kaisa', 'kai sa', 'kai\'sa'],
	kalista: ['kalista'],
	karma: ['karma'],
	karthus: ['karthus'],
	kassadin: ['kassadin', 'kass'],
	katarina: ['katarina', 'kat'],
	kayle: ['kayle'],
	kayn: ['kayn', 'rhaast'],
	kennen: ['kennen'],
	khazix: ['khazix', 'kha\'zix', 'kha zix'],
	kindred: ['kindred'],
	kled: ['kled'],
	kogmaw: ['kogmaw', 'kog\'maw', 'kog maw'],
	leblanc: ['leblanc', 'le blanc'],
	leesin: ['leesin', 'lee sin', 'lee'],
	leona: ['leona'],
	lillia: ['lillia'],
	lissandra: ['lissandra', 'liss'],
	lucian: ['lucian'],
	lulu: ['lulu'],
	lux: ['lux'],
	malphite: ['malphite', 'rock', 'peñon'],
	malzahar: ['malzahar', 'malz'],
	maokai: ['maokai'],
	masterYi: ['masteryi', 'yi', 'master yi'],
	milio: ['milio'],
	missfortune: ['missfortune', 'miss fortune', 'mf'],
	mordekaiser: ['mordekaiser', 'morde', 'mord'],
	morgana: ['morgana'],
	naafiri: ['naafiri', 'nafiri'],
	nami: ['nami'],
	nasus: ['nasus'],
	nautilus: ['nautilus', 'naut'],
	neeko: ['neeko'],
	nidalee: ['nidalee'],
	nilah: ['nilah'],
	nocturne: ['nocturne', 'noct'],
	nunu: ['nunu', 'nunu&willump', 'nunu&willump', 'nunu and willump', 'nunu and willump', 'nunu y willump', 'willump'],
	olaf: ['olaf'],
	orianna: ['orianna', 'ori'],
	ornn: ['ornn'],
	pantheon: ['pantheon', 'panth'],
	poppy: ['poppy'],
	pyke: ['pyke'],
	qiyana: ['qiyana'],
	quinn: ['quinn'],
	rakan: ['rakan'],
	rammus: ['rammus', 'ok'],
	reksai: ['reksai', 'rek\'sai', 'rek sai'],
	rell: ['rell'],
	renata: ['renata', 'glasc', 'renata glasc'],
	renekton: ['renekton', 'renek'],
	rengar: ['rengar'],
	riven: ['riven'],
	rumble: ['rumble'],
	ryze: ['ryze'],
	samira: ['samira'],
	sejuani: ['sejuani', 'sej'],
	senna: ['senna'],
	seraphine: ['seraphine'],
	sett: ['sett'],
	shaco: ['shaco'],
	shen: ['shen'],
	shyvana: ['shyvana'],
	singed: ['singed'],
	sion: ['sion'],
	sivir: ['sivir'],
	skarner: ['skarner'],
	smolder: ['smolder'],
	sona: ['sona'],
	soraka: ['soraka'],
	swain: ['swain'],
	sylas: ['sylas'],
	syndra: ['syndra'],
	tahmkench: ['tahmkench', 'tahm kench', 'tahm', 'kench'],
	taliyah: ['taliyah'],
	talon: ['talon'],
	taric: ['taric'],
	teemo: ['teemo'],
	thresh: ['thresh'],
	tristana: ['tristana'],
	trundle: ['trundle'],
	tryndamere: ['tryndamere', 'trynda'],
	twistedfate: ['twistedfate', 'twisted fate', 'tf'],
	twitch: ['twitch'],
	udyr: ['udyr'],
	urgot: ['urgot'],
	varus: ['varus'],
	vayne: ['vayne'],
	veigar: ['veigar'],
	velkoz: ['velkoz', 'vel\'koz', 'vel koz'],
	vex: ['vex'],
	vi: ['vi'],
	viego: ['viego'],
	viktor: ['viktor'],
	vladimir: ['vladimir', 'vlad'],
	volibear: ['volibear', 'voli'],
	warwick: ['warwick', 'ww'],
	wukong: ['wukong'],
	xayah: ['xayah'],
	xerath: ['xerath'],
	xinzhao: ['xinzhao', 'xin zhao', 'xin'],
	yasuo: ['yasuo'],
	yone: ['yone'],
	yorick: ['yorick'],
	yuumi: ['yuumi'],
	zac: ['zac'],
	zed: ['zed'],
	zeri: ['zeri'],
	ziggs: ['ziggs'],
	zilean: ['zilean'],
	zoe: ['zoe'],
	zyra: ['zyra'],
};

const getChampionFromAlias = (alias) => {
	const aliasLower = alias.toLowerCase();
	const champion = Object.keys(CHAMPION_LIST).find((key) => CHAMPION_LIST[key].includes(aliasLower));
	return champion;
};

module.exports = {
	CHAMPION_LIST,
	getChampionFromAlias,
};